// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyvuknecrkoltomrkhgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dnVrbmVjcmtvbHRvbXJraGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTY0MDcsImV4cCI6MjA2MDQ3MjQwN30.pcUvXDkO5HzWKD5arJbat2tZIyXXb1zmvmRiDLIIWnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);